//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferry.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferry.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting import....
        /// </summary>
        internal static string AbortingImport {
            get {
                return ResourceManager.GetString("AbortingImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to abort import?.
        /// </summary>
        internal static string AreYouSureToAbortImport {
            get {
                return ResourceManager.GetString("AreYouSureToAbortImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot log the exception.
        /// </summary>
        internal static string CannotLogException {
            get {
                return ResourceManager.GetString("CannotLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company group saved successfully.
        /// </summary>
        internal static string CoGroupSavedSuccessfully {
            get {
                return ResourceManager.GetString("CoGroupSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing of this company is already in progress. Cannot delete.
        /// </summary>
        internal static string CompanyPeriodAlreadyImportingCannotDelete {
            get {
                return ResourceManager.GetString("CompanyPeriodAlreadyImportingCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing of this company is already in progress. Cannot do parallel import.
        /// </summary>
        internal static string CompanyPeriodAlreadyImportingCannotImport {
            get {
                return ResourceManager.GetString("CompanyPeriodAlreadyImportingCannotImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this company group?
        ///
        ///WARNING: Deleting company group will delete data..
        /// </summary>
        internal static string DeleteCompanyGroup {
            get {
                return ResourceManager.GetString("DeleteCompanyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this period?.
        /// </summary>
        internal static string DeleteCompanyPeriod {
            get {
                return ResourceManager.GetString("DeleteCompanyPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This company period is imported. Are you sure to delete?
        ///
        ///WARNING: Deleting company period will delete imported data..
        /// </summary>
        internal static string DeleteImportedCompanyPeriod {
            get {
                return ResourceManager.GetString("DeleteImportedCompanyPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract, Trasform and Loading in progress.
        /// </summary>
        internal static string EtlInProgress {
            get {
                return ResourceManager.GetString("EtlInProgress", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Foresight {
            get {
                object obj = ResourceManager.GetObject("Foresight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import aborted.
        /// </summary>
        internal static string ImportAborted {
            get {
                return ResourceManager.GetString("ImportAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing data failed.
        /// </summary>
        internal static string ImportDataFailed {
            get {
                return ResourceManager.GetString("ImportDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing data successfull.
        /// </summary>
        internal static string ImportDataSuccessfull {
            get {
                return ResourceManager.GetString("ImportDataSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No import provider found for this data path
        ///
        ///Make sure following files exists:
        ///
        ///For EASY: check CO_GRP.DBF and CO_FILE.DBF
        ///For MCS: check MNCOM.DBF and MNGRP.DBF
        ///For TCS: check RPCOM.DBF and RPGRP.DBF.
        /// </summary>
        internal static string ImportProviderFilesNotFound {
            get {
                return ResourceManager.GetString("ImportProviderFilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started at: {0}.
        /// </summary>
        internal static string ImportStartedAt {
            get {
                return ResourceManager.GetString("ImportStartedAt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This period is already imported. Want to import again ?.
        /// </summary>
        internal static string PeriodIsAlreadyImported {
            get {
                return ResourceManager.GetString("PeriodIsAlreadyImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a data path.
        /// </summary>
        internal static string SelectDataPath {
            get {
                return ResourceManager.GetString("SelectDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select import company data folder:.
        /// </summary>
        internal static string SelectImportCompanyDataFolder {
            get {
                return ResourceManager.GetString("SelectImportCompanyDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select import data folder:.
        /// </summary>
        internal static string SelectImportDataFolder {
            get {
                return ResourceManager.GetString("SelectImportDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foresight: Select or enter company group database file name.
        /// </summary>
        internal static string SelectOrEnterCompanyGroupDbFileName {
            get {
                return ResourceManager.GetString("SelectOrEnterCompanyGroupDbFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting import....
        /// </summary>
        internal static string StartingImporting {
            get {
                return ResourceManager.GetString("StartingImporting", resourceCulture);
            }
        }
    }
}
