//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScalableApps.Foresight.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScalableApps.Foresight.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an open transaction exist. Cannot start new transacion again.
        /// </summary>
        internal static string CannotStartNewTransaction {
            get {
                return ResourceManager.GetString("CannotStartNewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified company group &apos;{0}&apos; already exist.
        /// </summary>
        internal static string CompanyGroupAlreadyExists {
            get {
                return ResourceManager.GetString("CompanyGroupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import data from {0}.
        ///
        ///Possible source data path is in use by another.
        ///
        ///Note: {1}.
        /// </summary>
        internal static string CouldNotImportDataSourceIsInUse {
            get {
                return ResourceManager.GetString("CouldNotImportDataSourceIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file {0} doesn&apos;t exist.
        /// </summary>
        internal static string DatabaseFileNotFound {
            get {
                return ResourceManager.GetString("DatabaseFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Name.
        /// </summary>
        internal static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foresight template file not found.
        /// </summary>
        internal static string ForesightTemplateNotFound {
            get {
                return ResourceManager.GetString("ForesightTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger Group File: {0} not found.
        /// </summary>
        internal static string GeneralLedgerGroupFileNotFound {
            get {
                return ResourceManager.GetString("GeneralLedgerGroupFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified {0} genus not supported.
        /// </summary>
        internal static string GenusNotSupported {
            get {
                return ResourceManager.GetString("GenusNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified importer {0} not supported.
        /// </summary>
        internal static string ImporterNotSupported {
            get {
                return ResourceManager.GetString("ImporterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified source data folder {0} is invalid..
        /// </summary>
        internal static string InvalidSourceDataPath {
            get {
                return ResourceManager.GetString("InvalidSourceDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        internal static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This period already exists.
        /// </summary>
        internal static string PeriodAlreadyExists {
            get {
                return ResourceManager.GetString("PeriodAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified source database provider {0} not supported.
        /// </summary>
        internal static string SourceDatabaseProviderNotSupported {
            get {
                return ResourceManager.GetString("SourceDatabaseProviderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified target database provider {0} not supported.
        /// </summary>
        internal static string TargetDatabaseProviderNotSupported {
            get {
                return ResourceManager.GetString("TargetDatabaseProviderNotSupported", resourceCulture);
            }
        }
    }
}
